local config = "plugins.configs.";

require("core.keymaps")
require("plugins.lazy")
require(config .. "lsp")
require(config .. "dap")
require(config .. "tsc")
require(config .. "options")
require(config .. "colorscheme")
require(config .. "cmp")
require(config .. "telescope")
require(config .. "gitsigns")
require(config .. "treesitter")
require(config .. "nvim-tree")
require(config .. "lualine")
require(config .. "toggleterm")
require(config .. "project")
require(config .. "impatient")
require(config .. "alpha")
require(config .. "whichkey")
require(config .. "autocommands")
require(config .. "nvim-ts-autotag")
require(config .. "todo-comments")
require(config .. "psql")
require(config .. "neodev")
require(config .. "luasnippets")
require(config .. "live-server")
require(config .. "mini")
require(config .. "neorg")
require(config .. "template")
require(config .. "colorizer")
require(config .. "plantuml")
