require("core.keymaps")
require("plugins.lazy")
require("plugins.configs.options")
require("plugins.configs.colorscheme")
require("plugins.configs.cmp")
require("plugins.configs.lsp")
require("plugins.configs.telescope")
require("plugins.configs.gitsigns")
require("plugins.configs.treesitter")
require("plugins.configs.nvim-tree")
require("plugins.configs.lualine")
require("plugins.configs.toggleterm")
require("plugins.configs.project")
require("plugins.configs.impatient")
require("plugins.configs.alpha")
require("plugins.configs.whichkey")
require("plugins.configs.autocommands")
require("plugins.configs.dap")
require("plugins.configs.nvim-ts-autotag")
require("plugins.configs.todo-comments")
require("plugins.configs.psql")
require("plugins.configs.neodev")
require("plugins.configs.luasnippets")
require("plugins.configs.live-server")
require("plugins.configs.tsc")
require("plugins.configs.mini")
require("plugins.configs.neorg")
require("plugins.configs.template")
require("plugins.configs.colorizer")
require("plugins.configs.plantuml")

-- disable netrw at the very start of your init.lua nvim-tree
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
