require("core.options")
require("core.keymaps")
require("core.plugins")
require("core.colorscheme")
require("core.cmp")
require("core.lsp")
require("core.telescope")
require("core.gitsigns")
require("core.treesitter")
require("core.nvim-tree")
require("core.lualine")
require("core.toggleterm")
require("core.project")
require("core.impatient")
require("core.alpha")
require("core.whichkey")
require("core.autocommands")
require("core.dap")
require("core.nvim-ts-autotag")
require("core.todo-comments")
require("core.psql")
require("core.neodev")
require("core.luasnippets")
require("core.live-server")
require("core.tsc")
require("core.mini")
require("core.neorg")
require("core.template")
require("core.colorizer")
require("core.plantuml")

-- disable netrw at the very start of your init.lua nvim-tree
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
